version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    versioning-strategy: increase
    groups:
      jest:
        patterns:
          - "*jest*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
